#!/usr/bin/env python3
# coding=utf-8

import depthai as dai
import cv2
from pathlib import Path
root = Path(__file__).parent.resolve()

if globals().get("__compiled__"):
    root = Path(__compiled__.containing_dir).resolve()

# Create pipeline
pipeline = dai.Pipeline()

# Define sources and output
camRgb = pipeline.create(dai.node.ColorCamera)
videoEnc = pipeline.create(dai.node.VideoEncoder)
xout = pipeline.create(dai.node.XLinkOut)

xout.setStreamName('h265')

xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")
camRgb.isp.link(xoutRgb.input)

# Properties
camRgb.setBoardSocket(dai.CameraBoardSocket.CAM_A)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_4_K)
videoEnc.setDefaultProfilePreset(30, dai.VideoEncoderProperties.Profile.H265_MAIN)

# Linking
camRgb.video.link(videoEnc.input)
videoEnc.bitstream.link(xout.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:

    # Output queue will be used to get the encoded data from the output defined above
    q = device.getOutputQueue(name="h265", maxSize=30, blocking=True)
    qRgb = device.getOutputQueue(name="rgb", maxSize=30, blocking=True)

    cv2.namedWindow("rgb", cv2.WINDOW_NORMAL)

    # The .h265 file is a raw stream file (not playable yet)
    with open(root.joinpath('video.h265'), 'wb') as videoFile:
        print("Press Ctrl+C to stop encoding...")
        try:
            while True:
                inRgb = qRgb.tryGet()  # Non-blocking call, will return a new data that has arrived or None otherwise
                if inRgb is not None:
                    frame = inRgb.getCvFrame()
                    cv2.imshow("rgb", frame)

                key = cv2.waitKey(1) & 0xff
                if key == ord("q"):
                    break

                h265Packet = q.get()  # Blocking call, will wait until a new data has arrived
                h265Packet.getData().tofile(videoFile)  # Appends the packet data to the opened file
        except KeyboardInterrupt:
            # Keyboard interrupt (Ctrl + C) detected
            pass

    print("To view the encoded data, convert the stream file (.h265) into a video file (.mp4) using a command below:")
    print("ffmpeg -framerate 30 -i video.h265 -c copy video.mp4")
